name: Flutter CI

on:
  push:
    branches:
      - main
      - develop
      - feature/*
      - fix/*
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5' # Especifique uma versão estável explicitamente

      - name: Verify Flutter Installation
        run: flutter --version

      - name: Clear Flutter Cache
        run: flutter clean

      - name: Install dependencies
        run: flutter pub get

      - name: Generate mocks
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Run User Preferences Tests
        run: flutter test test/user_preferences_tests.dart
  
      - name: Run Login Tests
        run: flutter test test/login_test.dart
  
      - name: Run Strong Password Tests
        run: flutter test test/strong_password_test.dart
